apiVersion: app.kiegroup.org/v1beta1
kind: KogitoSupportingService
metadata:
  name: job-service
spec:
  serviceType: JobsService
  replicas: 1
  image: quay.io/kiegroup/kogito-jobs-service
  infra:
     - infinispan-infra
     - kafka-infra
  env:
  - name: quarkus.infinispan-client.sasl-mechanism
    value: SCRAM-SHA-256
  - name: ENABLE_EVENTS
    value: "true"
  - name: KOGITO_JOBS_PROPS
    value: -Dquarkus-profile=events-support -D%events-support.quarkus.http.port=8080 -D%events-support.kafka.bootstrap.servers=http://10.101.127.211:9092
                         -D%events-support.mp.messaging.outgoing.kogito-job-service-job-status-events.bootstrap.servers=http://10.101.127.211:9092
                         -Dkogito.service.url=http://10.105.221.125:8080