apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: service-approval-process
spec:
  replicas: 1
  image: docker.demor.sk/kogito/service-approval-process:test
  infra:
    - infinispan-infra
    - kafka-infra
  env:
    - name: QUARKUS_INFINISPAN_CLIENT_SASL_MECHANISM
      value: SCRAM-SHA-512
    - name: kogito.dataindex.http.url
      value: http://10.96.168.116:80
    - name: kogito.dataindex.ws.url 
      value: ws://10.96.168.116:80
    - name: kogito.service.url
      value: http://10.100.113.150:80
    - name: kogito.jobs-service.url
      value: http://10.101.204.150:80
    - name: kafka.bootstrap.servers
      value: http://10.100.139.107:9092